# Generated by Django 4.1.5 on 2023-04-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acategory',
            options={},
        ),
        migrations.DeleteModel(
            name='Trendy_Products',
        ),
    ]
