# Generated by Django 4.1.5 on 2023-04-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trendy_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='صورة شخصية'),
        ),
    ]
