# Generated by Django 4.1.5 on 2023-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_profile_addres_remove_profile_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='صورة شخصية'),
        ),
    ]
