# Generated by Django 4.1.5 on 2023-04-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
