# Generated by Django 3.2.18 on 2023-04-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230417_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone number2'),
        ),
    ]
