# Generated by Django 4.2 on 2023-05-27 15:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='card_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
