# Generated by Django 4.2 on 2023-05-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_billing_details_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='Products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.trendy_products'),
        ),
    ]
