# Generated by Django 4.2 on 2023-05-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_billing_details_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
