# Generated by Django 4.2 on 2023-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_billing_details_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_details',
            name='card_expiration_date',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='card_number',
        ),
        migrations.AddField(
            model_name='billing_details',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
