## دا مثال للشرح بس
## دي عبارة عن ديكشناري 

{'ALLUSERSPROFILE': 'C:\\ProgramData',   
 'APPDATA': 'C:\\Users\\elmooo\\AppData\\Roaming',   
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',   
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',   
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',   
 'COMPUTERNAME': 'DESKTOP-DVEITCC',   
 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',   
 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',   
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',   
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',   
 'HOMEDRIVE': 'C:',   
 'HOMEPATH': '\\Users\\elmooo',   
 'LOCALAPPDATA': 'C:\\Users\\elmooo\\AppData\\Local',   
 'LOGONSERVER': '\\\\DESKTOP-DVEITCC',   
 'NUMBER_OF_PROCESSORS': '4',   
 'ONEDRIVE': 'C:\\Users\\elmooo\\OneDrive - Alexandria University',   
 'ONEDRIVECOMMERCIAL': 'C:\\Users\\elmooo\\OneDrive - Alexandria University',   
 'OS': 'Windows_NT',  # دا نظام التشغيل الي اليوزر بيستخدمه مثلا  
 'PATH': 'C:\\Users\\elmooo\\Desktop\\test2\\venv_test\\Scripts;C:\\Users\\elmooo;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Users\\elmooo\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\elmooo\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\elmooo\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\elmooo\\AppData\\Local\\Programs\\Microsoft VS Code\\bin',   
 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',   
 'PROCESSOR_ARCHITECTURE': 'AMD64',   
 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',   
 'PROCESSOR_LEVEL': '6',   
 'PROCESSOR_REVISION': '3a09',   
 'PROGRAMDATA': 'C:\\ProgramData',   
 'PROGRAMFILES': 'C:\\Program Files',   
 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',   
 'PROGRAMW6432': 'C:\\Program Files',   
 'PROMPT': '(venv_test) $P$G',   
 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',   
 'PUBLIC': 'C:\\Users\\Public',   
 'SESSIONNAME': 'Console',   
 'SYSTEMDRIVE': 'C:',   
 'SYSTEMROOT': 'C:\\Windows',   
 'TEMP': 'C:\\Users\\elmooo\\AppData\\Local\\Temp',   
 'TMP': 'C:\\Users\\elmooo\\AppData\\Local\\Temp',   
 'USERDOMAIN': 'DESKTOP-DVEITCC',   
 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-DVEITCC',   
 'USERNAME': 'elmooo',   ##
 'USERPROFILE': 'C:\\Users\\elmooo',   
 'VIRTUAL_ENV': 'C:\\Users\\elmooo\\Desktop\\test2\\venv_test',   
 'WINDIR': 'C:\\Windows',   
 '_OLD_VIRTUAL_PATH': 'C:\\Users\\elmooo;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Users\\elmooo\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\elmooo\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\elmooo\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\elmooo\\AppData\\Local\\Programs\\Microsoft VS Code\\bin',   
 '_OLD_VIRTUAL_PROMPT': '$P$G',   
 'DJANGO_SETTINGS_MODULE': 'testusr.settings',   
 'RUN_MAIN': 'true',   
 'SERVER_NAME': 'DESKTOP-DVEITCC',   
 'GATEWAY_INTERFACE': 'CGI/1.1',   
 'SERVER_PORT': '8000',   
 'REMOTE_HOST': '',   
 'CONTENT_LENGTH': '',   
 'SCRIPT_NAME': '',   
 'SERVER_PROTOCOL': 'HTTP/1.1',   
 'SERVER_SOFTWARE': 'WSGIServer/0.2',   
 'REQUEST_METHOD': 'GET',   
 'PATH_INFO': '/hi',   
 'QUERY_STRING': '',   
 'REMOTE_ADDR': '127.0.0.1',   
 'CONTENT_TYPE': 'text/plain',   
 'HTTP_HOST': '127.0.0.1:8000',   
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0',   
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',   
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',   
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',   
 'HTTP_CONNECTION': 'keep-alive',   
 'HTTP_COOKIE': 'csrftoken=g87Rx92pZGIap2uurQcan9f4Zl8ws536',   
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',   
 'HTTP_SEC_FETCH_DEST': 'document',   
 'HTTP_SEC_FETCH_MODE': 'navigate',   
 'HTTP_SEC_FETCH_SITE': 'none',   
 'HTTP_SEC_FETCH_USER': '?1',   
 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000001FF6453FCA0>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http',   
 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>, 'CSRF_COOKIE': 'g87Rx92pZGIap2uurQcan9f4Zl8ws536'}